### ISSUE TITLE
подготовка за инсталиране на Kindle 3 Wi Fi (3.4)

### ISSUE THREAD

**Issue by stanilm** [kaloyan-raev/chitanka4kindle#2]
Здравейте ,
Използвам Kindle 3 Wi Fi (Version 3.4 B008)Моля за малко по- подробно обяснение за инсталиране на приложението.По точно подготовката на четеца. Стигнах до стъпка 3 от подготовката и не мога дапродължа нататък.Не мога да разбера как да използвам инсталираното USBnetwork за да продължа нататък

**Comment by kaloyan-raev** [comment]
В архива на USBnetwork, който сте свалили и инсталирани, има файл с име README_FIRST.txt. Там е описано доста подробно как се използва USBnetwork. Със сигурност не е елементарно и се изискват определни познания по операционни системи.

Кажете по-конкретно къде се затруднявате и ще се опитам да разясня.

**Comment by stanilm** [comment]
Здравейте,
Благодаря за готовността от ваша страна, да помогнете. Към момента съм извършил стъпка 1 и 2.  От Линкът за стъпка 3 съм свалил на PC-то с ОС Windows 7 - 5бр архива developer.keystore. Питането ми е директно ли се копират на Киндъла , или трябва да се стартира и използва USBnetwork. Следвайки тези инструкции "Copying this developer.keystore to your /var/local/java/keystore/ and restarting the Kindle will allow using any of these developer's Kindlet." не мога нищо да направя,тъй като не виждам на Киндъл устройството въпросните директории /var/local/java/keystore/. Това ме кара да се замисля дали не се използва USBnetwork.След инсталирането на  USBnetwork, необходими ли са последващи действия и команди чрез Киндъл за работа с USBnetwork.

**Comment by kaloyan-raev** [comment]
Да, необходимо е използването на USBnetwork. Това, което се появява като папки при нормалното свързване на Киндъл, е само една малка част от файловата система на устройството, която е предвидена да се използва от потребителя, за да си прехвърля книги. Въпросната директория /var/local/java/keystore/ е в "системната" част на файловата система, която по принцип е невидима.

USBnetwork всъщност дава възможност да се осъществи мрежова връзка между компютъра и Киндъл посредством USB кабела. При правилна конфигурация на USBnetwork Киндъл ще е достъпен чрез IP от компютъра. След това се използват популярни инструменти като SSH и SCP за редактиране и прехвърляне на файлове.

Всичко това е подробно описано в споменатия README_FIRST.txt файл. Инструкциите, обаче, са за операционни системи, базирани на Unix, като Linux и Mac OS X. На Windows може би също може да се получи, но и аз не мога да дам конкретни инструкции.
