### ISSUE TITLE
Не е възможно да се свалят книги java exceptions 

### ISSUE THREAD

**Issue by bmihovski** [kaloyan-raev/chitanka4kindle#3]
Здравейте,

Мога да преглеждам каталога на читанка, но не мога да свалям книги.
Снимка с грешките е прикачена по-долу.
![dsc_0018](https://cloud.githubusercontent.com/assets/4339683/7899806/ef4dc40e-072a-11e5-938d-3375674c6f33.JPG)

**Comment by kaloyan-raev** [comment]
Книгите се свалят от http://bb.bulexpo-bg.com/ - огледало на Читанка, на което книгите са конвертирани във формат MOBI, който се чете от Kindle.

Възможно е в момента, в който е възникнала грешката, огледалният сайт да е имал проблем. Преди малко проверих и свалих успешно книга.

При теб проблемът все още ли е наличен?

**Comment by bmihovski** [comment]
В момента мога да свалям книги, но е нужен рестарт на устройството за да ги достъпя. Прозореца с грешка си остава, нот не мисля че това е голям проблем.

**Comment by zdravkonoev** [comment]
Здравейте при мен излиза подобно грешка коятозапочва последния начин:
java.security.AccessControlException: access denied 
(java.io.FilePermission /mnt/us/documents/28926.mobi write)
бихте ли ми помогнали с разбирането на проблема?
