### ISSUE TITLE
Не е възможно да се свалят книги java exceptions 

### ISSUE THREAD

**Issue by zdravkonoev** [kaloyan-raev/chitanka4kindle#4]
Здравейте при мен излиза подобна грешка която започва по следният начин:
 java.security.AccessControlException: access denied 
 (java.io.FilePermission /mnt/us/documents/28926.mobi write)
 бихте ли ми помогнали с разбирането на проблема?

**Comment by kaloyan-raev** [comment]
Привет!
Погледни коментарите в тази статия: http://hitrini.blogspot.com/2014/02/chitanka-for-kindle.html
Ако си с Kindle 4 трябва да се добави допълнителен permission в external.policy, който по принцип си е наличен в Kindle 3.

**Comment by zdravkonoev** [comment]
Много благодаря, това реши проблема с Kindle 4 и явно е задължително да се добави този ред най-отдолу в файла с пермисии за да работи апликацията

grant {
 permission java.io.FilePermission "/mnt/us/-", "read,write,execute";
};
