### ISSUE TITLE
java грешка след като зареди началния екран на Читанка

### ISSUE THREAD

**Issue by zdravkonoev** [kaloyan-raev/chitanka4kindle#5]
Здравейте, апликацията работи перфектно няколко месеца, но през последните 6 дава все един и същи проблем след като зареди менюто на Читанка.

добавям снимка т.к. текста е доста за преписване. Благодаря Ви и поздрави.
![wp_20160808_22_35_26_rich](https://cloud.githubusercontent.com/assets/13738317/17493569/9fd28554-5db9-11e6-8f0e-7c749e3861eb.jpg)

**Comment by kaloyan-raev** [comment]
Благодаря за докладването на проблема. И извинения, че чак сега му обръщам внимание.

Проблемът е решен чрез https://github.com/kaloyan-raev/chitanka4kindle/commit/cc4627352d20e4b82203847ddbf86ae72946cf0c

Изтеглете файла chitanka.azw2 от [версия 1.0.1](https://github.com/kaloyan-raev/chitanka4kindle/releases/tag/1.0.1) и го копирайте на Киндъла.

**Comment by rakovm** [comment]
Здравейте, отскоро и при мен на киндле-а се показва същото нещо. Направих горното нещо и не помага :)
