### ISSUE TITLE
Проблем!

### ISSUE THREAD

**Issue by ProstoAZ** [kaloyan-raev/chitanka4kindle#6]
Пич, надявам се да четеш точи проект. 

Идеята е изключително добра.

Но инструкциите ти са БРУТАЛНИ. 

Какво пречеше да опишеш всяка стъпка, вместо да ни оставяш да се мъчим като грешни дяволи?

Стигнах дотук: 

Използвайки USBNetwork, редактирайте файла /opt/amazon/ebook/security/external.policy. В секцията grant signedBy "Kindlet" добавете следния ред: 

Как се използва този USBNetwork? КЪДЕ Е тъпият файл за редакция /opt/amazon/ebook/security/external.policy.? Къде, къде, къде?!

Благодаря за всичко, но някак е тъпо да прокараш идея, но само за програмисти. 

Моля те, дай инструкции!

**Comment by ProstoAZ** [comment]
Хей, неграмотнико, само недобре възпитаните дават лични квалификации и обидни епитети. Но животът ще те научи. 

Въпросът ми не бе към теб, а към Калоян. 

И ако си грамотен наистина, и разбираш текстовете и значението им, ще видиш, че аз обида нямам към никого.

**Comment by bmihovski** [comment]
Разбирам и виждам арогантното ти поведение, присъщо на всеки средно статистически малоумник, на който целият свят му е длъжен.

**Comment by ProstoAZ** [comment]
Никой за нищо не ми е длъжен и поведението не е арогантно, а плод на гняв, пореден от над час лутане. 

В общи линии има титориал, но няма описание стъпка по стъпка как да... Не всички разбираме всичко. А от това: прочети и следвай инструкциите, дори там не мога да се ориентирам във всичко. 

За да работи нещо масово, се насочва към средностатистическите малоумници. Ако те не могат да се оправят, то какъв е смисълът да го ползват трима души?

И в крайна сметка написах, че идеята е много добра, че моля за инструкции, които се разграничават от прочете там, защото не успявам да се ориентирам. 

А това, че описанията са брутални - брутални са. Бруто = грозно. Ще бъде доста по-лесно, ако се направи хубаво. Ако имах време, бих се заел.

**Comment by bmihovski** [comment]
Няма как да е масово този мод е свързан с хакване на книгата, което не се поддържа от производителя и процедурата не е направена от автора на това приложение. За да инсталираш приложението се подразбира че си направил хакването (или знаеш как да го направиш). Относно гнева запази го за себе защото той е породен от незнание и тук никой не се интерсува от психологическото ти състояние. Как можеш да добиеш въпросното знание като прочетеш и следваш описанията от препратките. Аз направих така и успешно си инсталирах приложението. Ако мислиш че е не възможно да ги разбереш, по добре се откажи, защото следващият пристъп на гняв ще бъде породен от повредената ти електронна книга.

**Comment by ProstoAZ** [comment]
Всичко разбирам. Единственото, което не разбирам, е това:

Читанка за Kindle сваля избраната книга във флаш паметта на устройството. За да се появи книгата на главния екран на Kindle, е необходимо приложението да изпълни специален скрипт. Настойките по подразбиране забраняват изпълнението на такива скриптове. Затова е нужно да се добави съответното разрешение.

Използвайки USBNetwork, редактирайте файла /opt/amazon/ebook/security/external.policy. В секцията grant signedBy "Kindlet" добавете следния ред:

permission java.io.FilePermission "<<ALL FILES>>", "execute";

Знам какво трябва да се направи, но не знам къде се намира този файл OPT... Ако го намеря, аз другото ще си го направя, защото е елементарно. 

И ако си толкова мъдър, па вземи кажи, или не се занимавай. 

Питам просто и ясно - къде да видя директория opt/amazon/ebook/security/external.policy. 
Останалото ще си го направя и сам. 

Можеш ли да помогнеш, или можеш да пишеш дълги и безсмислени текстове под темата в проекта, която е за помощ и за не разбиращите, а не просто за гений и моралисти?

**Comment by bmihovski** [comment]
Файла се намира в директорията /opt който можеш да достъпиш като направиш ssh свързване към книгата, препоръчвам ти за връзка от твоят компютър да използваш програмата putty. За повече информация http://www.tldp.org/LDP/intro-linux/html/sect_03_01.html
Отношението ти продължава да не надменно, ако искаш помощ, трябва да смениш, тона и да изполваш повече думите "моля" и "благодаря".

**Comment by ProstoAZ** [comment]
Благодаря и весели празници.

**Comment by bmihovski** [comment]
Няма защо, успя ли да намериш файла?

**Comment by ProstoAZ** [comment]
Не. 

Като цяло - ползвам мак. Но изобщо не схващам как да направя ssh връзка, защото досега не съм правил такава. Иначе достъпя ли файла, ще го променя. Но не мога да го свържа. Няма нито едно видео, нито един титориал как точно става. 

Всичко друго съм направил, демек трябва само да променя този ред и всичко ще работи. Оказва се обаче, че загубих 3 часа в тази работа и не постигнах успех. 

Всяка следваща минута лутане е ужасно прахосничество на време и днес реално нищо не свърших. 

Ще си казвам книгите по стария си начин. 

Стори ми се интересно да го направя, защото обичам да правя такива неща, но тук ми е невъзможно. 

Благодаря все пак. Явно наистина е за големи специалисти, не за хора като мен.

**Comment by bmihovski** [comment]
Аз съм със мак също през него хакнах и книгата. Под мак през launchpad в търсачката пишеш terminal и го отваряш. Примерни настройки как да се настрои мрежата може да се намери тук http://aming-blog.blogspot.ie/2010/05/kindle-usb-network-tethering.html
https://www.turnkeylinux.org/blog/kindle-root
През терминала се пише тази команда за свързване към устройството ssh 192.168.2.2
Точно това имах в предвид приложението не се инсталира трудно, но jailbreak си е играчка.

**Comment by kaloyan-raev** [comment]
@ProstoAZ Съгласен съм, че инструкциите не са подходящи за всеки. Изисква се поне някакъв опит с администриране на Linux системи. При липса на такъв, по-добре е човек да не се занимава, за да не си съсипе устройството.

Описание стъпка по стъпка би била доста трудоемък процес. За всяка операционна система (Windows, Linux, Mac OS X) в различните им варианти се използват различни инструменти. Има разлики в конкретните стъпки за различните версии на Kindle устройствата. Точно по тази причина реших, че е по-добре да предоставя връзка към форума MobileRead, където инструкциите са описани в детайли.

Ако някой вярва, че може да опише инструкциите по-добър начин, ще се радвам да приема Pull Request с промяна в README файла.

@bmihovski Благодаря за отделеното време и енергия за помощ с този проблем!
