### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by rakovm** [kaloyan-raev/chitanka4kindle#8]
Hello,
After jailbreak and install, i tried to run it but its saying that the device is not registered as a Test Kindle to run this title. Please ask the developer to add this device to the list of registered Test Kindles. Can you help me?
Поздрави!

**Comment by rakovm** [comment]
I forgot to say my device is K3Gb

**Comment by kaloyan-raev** [comment]
Здравей!
Мисля, че това се получава с устройства, които не са регистрирани в Amazon. Ако това е случая, то устройството трябва да се регистрира и отново да се изпълни инсталатора на приложението Читанка. Няма нужда да се отключва наново.

**Comment by rakovm** [comment]
Здравей,
Това е! Много ти благодаря! Можеш да добавиш в инсталацията, че трябва Kindle-а да е регистриран. Има някой Kindle-и, които не могат да се регистрират, там трябва да се види как точно ще се действа.

Поздрави!

**Comment by kaloyan-raev** [comment]
Чудесно!
Ще добавя изискването Kindle да е регистриран.

За устройствата, които не могат да се регистрират, няма надежда. Amazon така са направили Kindle, че да изтрива developer.keystore по време на стартиране, ако устройството не е регистрирано. Приложенията (т.нар. Kindlet-и) не могат да работят без този сертификат.
